### ISSUE TITLE
ValueError: cannot convert float NaN to integer

### ISSUE THREAD

**Issue by zubair9703** [PratyushTripathy/Landsat-Classification-Using-Convolution-Neural-Network#3]
Hi,
i am following your procedure and code to perform classification and i have encountered following error
![Screenshot 2022-02-06 161340](https://user-images.githubusercontent.com/92041481/152677272-670d9b4f-4259-4a43-b513-2591e84c068d.png)
r

**Comment by PratyushTripathy** [comment]
@zubair9703 In line 14, replace both the "%d" with "%f".

**Comment by PratyushTripathy** [comment]
@zubair9703 please add the following line of code above the first print statement (line 12).
`features[np.isnan(features)] = 0`
