### ISSUE TITLE
Error in the third part

### ISSUE THREAD

**Issue by zafor44** [PratyushTripathy/Landsat-Classification-Using-Convolution-Neural-Network#5]
![error 1](https://user-images.githubusercontent.com/95949556/167106452-fc55a865-a090-487b-adf0-e705efcd3fab.JPG)
![error 2](https://user-images.githubusercontent.com/95949556/167106466-43e802b5-383c-4e81-9db7-f57ecc0beeb2.JPG)

**Comment by PratyushTripathy** [comment]
Before the third part, where you prepare tensors for prediction, you have created image chips of size 11 by 11. But the model expects a 7 by 7 image. In the below line, change `kSize` from 11 to 7. That should solve the problem. Let me know if it does not.

`new_features = CNNdataGenerator(featuresHyderabad, kSize=11)`

**Comment by zafor44** [comment]
Thank you so much, sir.
fixed the issue.
